# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moj-dynamiczny-pvc
spec:
  storageClassName: managed # Musi pasować do nazwy StorageClass
  accessModes:
    - ReadWriteOnce # Ten tryb dostępu musi być wspierany przez PV/StorageClass
  resources:
    requests:
      storage: 10Gi # Żądany rozmiar pamięci 