apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todos-ingress-tls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dawidapp.mooo.com
    secretName: dawidapp.mooo.com
  rules:
  - host: dawidapp.mooo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todos-web
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: todos-api
            port:
              number: 3001 