apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-report
  namespace: cwiczenia
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report
            image: busybox:latest
            command: ["/bin/sh", "-c"]
            args: ["echo 'Hourly report generated at $(date)'"]
          restartPolicy: OnFailure

