apiVersion: batch/v1
kind: Job
metadata:
  name: timeout-job
  namespace: cwiczenia
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: sleeper
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args: ["sleep 300"]
      restartPolicy: Never

