apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: cwiczenia
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: cwiczenia
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

