apiVersion: v1
kind: Pod
metadata:
  name: private-image-pod
  namespace: cwiczenia
spec:
  serviceAccountName: image-puller
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

