apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-normal
  namespace: cwiczenia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-normal
  template:
    metadata:
      labels:
        app: nginx-normal
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

